import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

// Components
import Calendar from './components/schedule/Calendar';
import Header from './components/Header';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>FH App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header headline={"LBL_CAFE"} subheadline={"Welcome to our"}/>
      <div className='mx-4'>
        <Calendar />
      </div>
    </>
  )
}
